trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'
  buildOutput: '.dist' # Output directory for publish

# Publish Blazor App
steps:
- script: dotnet publish --configuration $(buildConfiguration) --output $(buildOutput)
  displayName: 'Publish Blazor Site'

# Install netlify-cli
- script: npm install netlify-cli 
  displayName: 'Install netlify-cli'

# Deploy the wwwroot from the output directory
# The argument "--prod" deploys to production
- script: npx netlify deploy --prod --dir $(buildOutput)/wwwroot --site $(netlify_site_id) --auth $(netlify_api_key)
  displayName: 'Deploy site to Netlify'